/**
 * Names of the icons the app draws. The actual paths live in the view layer
 * (ui/primitives/iconPaths.tsx) because they are SVG markup; only the names
 * are domain vocabulary, so only the names belong here.
 */
export type IconName =
  | "arrow-down"
  | "arrow-left"
  | "bank"
  | "bell"
  | "bolt"
  | "bulb"
  | "card"
  | "check"
  | "chevron-down"
  | "chevron-right"
  | "clock"
  | "coffee"
  | "contrast"
  | "droplet"
  | "eye"
  | "eye-off"
  | "globe"
  | "heart"
  | "home"
  | "landmark"
  | "limit"
  | "lock"
  | "log-out"
  | "mail"
  | "more"
  | "phone"
  | "plus"
  | "qr"
  | "receipt"
  | "rotate"
  | "search"
  | "send"
  | "shield"
  | "snow"
  | "star"
  | "star-filled"
  | "target"
  | "trash"
  | "user"
  | "wallet";
